### ISSUE TITLE
Development model and basic governance

### ISSUE THREAD

**Issue by silverhook** [IFOSSLawBook/ifosslawbook#3]
We should set up some basic rules on how we develop this repository and how people can contribute.

The contribution policy will likely be a bit specific, as this is a book.

Bot for the development model, I suggest we adopt one of the more general approaches that:

- `master` branch is always stable and always contains the latest actual release (of course that is not the case right now, but we should still start early with it)
- `bugfix` branch is the development version (ideally a cutting-edge, but working version)
- any specific fixes and additions should go into its own branches before they are approved to be merged into the `bugfix` branch

**Comment by martinsramek** [comment]
Sure, sounds good.

**Comment by silverhook** [comment]
Great, will create a `bugfix` branch and write up a quick doc for the development model.

**Comment by silverhook** [comment]
Fixed in https://github.com/IFOSSLawBook/ifosslawbook/commit/9aed5992f7395dd66633f0f3b4773b6d8a3d9bb5

We might need to improve it later on though.
