### ISSUE TITLE
Set up a naming convention (or continue to rely on sorting.meta)

### ISSUE THREAD

**Issue by silverhook** [IFOSSLawBook/ifosslawbook#4]
Currently we rely on the `sorting.meta` file to set the order in which the book should be generated. Which works.

Another approach would be to decide a naming convention and rely on that for sorting.

One idea would be to adopt a similar approach to how udev rules (and other settings) work:

```
10 - Intro
20 - History
50 - Belgium
50 - Slovenia
50 - Italy
50 - Austria
90 - Authors
```

Which if you order it “alphanumerically” it would first parse the intro (10), then the history (20), then all the jurisdiction chapters by alphabetical order of their names (all are 50, so it orders them by alphabet), and in the end the authors (90).

I think this would simplify things, but I’m open to other suggestions.

Also, as mentioned before, `sorting.meta` works, so we can continue depending on that.

**Comment by LeChasseur** [comment]
Sounds good to me. This would allow to add new chapters in the right order.

**Comment by silverhook** [comment]
That is my idea behind it, yes. Any normal chapters can simply be added as `50 - $country_name.markdown` and they should be generated in the right order. Without the need to manually keep track of the order in a separate file.

It also leaves us with enough space to introduce new groups of chapters before or after, as well. If, e.g. later we introduce some FOSS licensing basics that we want to have after History, but before the jurisdiction analysis, we simply need to prepend them numbers between 30 (to leave space for extra History chapters, just in case) and 49.

**Comment by martinsramek** [comment]
I have renamed the files and amended the README.

**Comment by silverhook** [comment]
I think we can safely remove the files that still use the old naming convention.

BTW, a useful command to move/rename files within a git repository is `git mv`. I often forget it myself and then have to back-paddle and fix the mess I did when I just did a `mv` instead. ;)

**Comment by martinsramek** [comment]
Ok. I fixed the mess now.

**Comment by alpianon** [comment]
I agree on the naming convention, but the use of spaces must be avoided if we want to use make to build.
So source file names should be:

```
10-Intro
20-History
50-Belgium
50-Slovenia
50-Italy
50-Austria
90-Authors
```

**Comment by silverhook** [comment]
I think @alpianon’s suggestion makes sense

**Comment by martinsramek** [comment]
OK. I have updated the file names and the README.
