### ISSUE TITLE
Include numbering

### ISSUE THREAD

**Issue by LeChasseur** [IFOSSLawBook/ifosslawbook#5]
A numbering is to be included. I add a screenshot of the "original" version.
![DSC_0580](https://user-images.githubusercontent.com/1921914/58004434-7e801980-7ae3-11e9-80e7-11a73dc8f5cc.JPG)

**Comment by martinsramek** [comment]
Adding the --number-sections option in pandoc seems to solve the issue.

**Comment by silverhook** [comment]
This is how it looks now. If we need to shift numbers, let us know @LeChasseur. Although I think the top numbers are going to change whenever a new country chapter gets introduced, so those do not need to replicate the book’s numbers. The sub(sub)chapter numbers should be fine now though.

![Screenshot_20210420_112527](https://user-images.githubusercontent.com/3227264/115372469-37b56580-a1cb-11eb-8acd-e35050b5e346.png)
