### ISSUE TITLE
Include authors

### ISSUE THREAD

**Issue by martinsramek** [IFOSSLawBook/ifosslawbook#9]
Including authors from separate files is part of issue #1.
All the changes are done in the `include_authors` branch and will be merged into `pandoc_cleanup` once they're finished.

- [x] resolve issue with concatenating files with include-pandoc

- [x] add page breaks, so chapters begin on a new page

- [x] update README.md

**Comment by martinsramek** [comment]
Issue with include-pandoc still not resolved. Concatenating files messes up the lines somehow.

**Comment by martinsramek** [comment]
`include-pandoc` concatenates files differently than `pandoc`. It's necessary to include a blank line at the start of every file for it to be concatenated correctly.

**Comment by silverhook** [comment]
> It's necessary to include a blank line at the start of every file for it to be concatenated correctly.

For this reason, I think an old convention was (still is, but no-one follows it?) to always leave an empty line at the end of every text file. We could just explicitly state this convention needs to be followed.

Would this work, @martinsramek ?

**Comment by martinsramek** [comment]
> 
> 
> > It's necessary to include a blank line at the start of every file for it to be concatenated correctly.
> 
> For this reason, I think an old convention was (still is, but no-one follows it?) to always leave an empty line at the end of every text file. We could just explicitly state this convention needs to be followed.
> 
> Would this work, @martinsramek ?
Indeed, this works also. I like this solution more. A blank line at the beginning of a file seems weird.

**Comment by silverhook** [comment]
Ha! Apparently the [“empty last line” has to do with POSIX standard](https://stackoverflow.com/a/729795).

**Comment by martinsramek** [comment]
OK, I discovered the culprit. It was my editor which deleted empty lines at the end of a file. That's why I used the dumb workaround with the blank lines at the beginning of the files. Now every file has an empty line at the end and all is well.
